VideoStore/Controllers/VideosSearchController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VideoStore.Models;

namespace VideoStore.Controllers
{
    public class VideosSearchController : Controller
    {
        VideoStoreEntities db = new VideoStoreEntities();

        // Index Action that returns a search page
        public ActionResult Index()
        {
            return View();
        }

        //Search action being implemented
        public ActionResult Details(string search)
        {
            if (String.IsNullOrEmpty(search))
            {
                return HttpNotFound();
            }
            else
            {
                return View(db.Videos.Where(x => x.VideoName.Contains(search)).ToList());
            }
                

        }

        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Video video = db.Videos.Find(id);
        //    if (video == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(video);
        //}


    }
}

VideoStore/Views/VideosSearch/AddToCart.cshtml
@{
    ViewBag.Title = "AddToCart";
    Layout = "~/Views/Shared/_CustomerLayoutPage.cshtml";
}

<h2>AddToCart</h2>

VideoStore/Views/VideosSearch/Create.cshtml
@model VideoStore.Models.Video

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_CustomerLayoutPage.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Video</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.VideoName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VideoName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VideoName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VideoDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VideoDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VideoDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VideoGenre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VideoGenre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VideoGenre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VideoStore/Views/VideosSearch/Delete.cshtml
@model VideoStore.Models.Video

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_CustomerLayoutPage.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Video</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.VideoName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VideoName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VideoDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VideoDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VideoGenre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VideoGenre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

VideoStore/Views/VideosSearch/Details.cshtml
@model IEnumerable<VideoStore.Models.Video>

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_CustomerLayoutPage.cshtml";
}

<h3>Search Results</h3>

@*@using(Html.BeginForm("Details", "VideosSearch", FormMethod.Get))
{
    <b> Search Option: </b>
    @Html.TextBox("continue searching")<input type="submit" name="submit" value="search" />
}*@


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.VideoName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VideoDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VideoGenre)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.VideoName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VideoDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VideoGenre)
        </td>    
        <td>
            @Html.ActionLink("Add to Cart", "AddToCart", new { id = item.VideoID }) 
        </td>
    </tr>
}
    

</table>

VideoStore/Views/VideosSearch/Edit.cshtml
@model VideoStore.Models.Video

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_CustomerLayoutPage.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Video</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.VideoID)

        <div class="form-group">
            @Html.LabelFor(model => model.VideoName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VideoName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VideoName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VideoDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VideoDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VideoDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VideoGenre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VideoGenre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VideoGenre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VideoStore/Views/VideosSearch/Index.cshtml
@model IEnumerable<VideoStore.Models.Video>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_CustomerLayoutPage.cshtml";
}

<h3>Index</h3>

@*@using (Html.BeginForm("Details", "VideosSearch", FormMethod.Get))
{
    <b> Search Option: </b>
    @Html.TextBox("search")<input type="submit" name="submit" value="search" />
}*@


@using (Ajax.BeginForm(new AjaxOptions { HttpMethod = "get", InsertionMode = InsertionMode.Replace, UpdateTargetId = "VideosList" }))
{
    <input type="search" name="searchTerm"/>
    <input type="submit" value="Search By Name" />
}

<div id="VideosList">
    @foreach(var item in Model)
    {
        <div>
            <h4>
                @item.VideoName
            </h4>
            <div>
                @item.VideoGenre
            </div>
            <hr />
        </div>
    }
</div>