VideoStore/Models/Pract.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace VideoStore.Models
{
    public class Pract
    {
    }
}

VideoStore/Controllers/PractController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VideoStore.Models;

namespace VideoStore.Controllers
{
    public class PractController : Controller
    {
        VideoStoreEntities db = new VideoStoreEntities();
        // GET: Pract
        public ActionResult Index(string option, string search )
        {
            if(option == "name")
            {
                return View(db.Videos.Where(x => x.VideoName == search).ToList());
            }
            List<Video> VideosList = db.Videos.ToList();
            return View(VideosList);
        }
    }
}

VideoStore/Views/Pract/Index.cshtml
@model IEnumerable<VideoStore.Models.Video>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_CustomerLayoutPage.cshtml";
}

<h2>Index</h2>

@using(Html.BeginForm("Index", "Pract", FormMethod.Get))
{
    <b> Search Option: </b>
    @Html.RadioButton("option","name")<text>Name</text>
    @Html.TextBox("search")<input type="submit" name="submit" value="search" />
}

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.VideoName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VideoDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VideoGenre)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.VideoName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VideoDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VideoGenre)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.VideoID }) |
            @Html.ActionLink("Details", "Details", new { id=item.VideoID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.VideoID })
        </td>
    </tr>
}

</table>